### ISSUE TITLE
[Enhancement] Xenial logs

### ISSUE THREAD

**Issue by cibersheep** [bhdouglass/clickable#82]
Steps:
1. Update manifest.json to use Xenial framwork: `"framework" : "ubuntu-sdk-16.04"`
2. Don't update apparmor file: `"policy_version": 1.3` (should be `"policy_version": 16.04` for Xenial)
3. Run `clickable --xenial` and wait for app to be installed
4. App crashes on start
5. Run `cliclable logs`

Result: can't find app log error
Expected result: A list of possible reasons of the crash?

**Comment by bhdouglass** [comment]
I think the best course of action here is to make a nice error if the install fails.

**Comment by cibersheep** [comment]
Oh. That sounds like a plan. In my experience I though the problem was with logs in Xenial... So, yep. Installing error would be clear 💜

**Comment by bhdouglass** [comment]
I was going to put in some error messages for this, but it turns out that the problem isn't that it doesn't get installed correctly, but rather that it doesn't launch correctly. Clickable doesn't really have any way to know that. So the fix here would be to run `clickable review` on your app or the system should add some info to the log file when this happens.
